SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


CREATE TABLE `itemattributes` (
  `id` int(11) NOT NULL,
  `serverId` int(11) NOT NULL,
  `name` varchar(32) COLLATE utf8mb4_bin NOT NULL,
  `value` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `items` (
  `serverId` int(11) NOT NULL,
  `clientId` int(11) NOT NULL,
  `itemGroup` int(11) NOT NULL,
  `flags` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `otb` (
  `major` int(11) NOT NULL,
  `minor` int(11) NOT NULL,
  `build` int(11) NOT NULL,
  `csd` varchar(128) COLLATE utf8mb4_bin NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;


ALTER TABLE `itemattributes`
  ADD PRIMARY KEY (`id`),
  ADD KEY `FK_ITEMS_SERVERID` (`serverId`);

ALTER TABLE `items`
  ADD PRIMARY KEY (`serverId`);


ALTER TABLE `itemattributes`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;


ALTER TABLE `itemattributes`
  ADD CONSTRAINT `FK_ITEMS_SERVERID` FOREIGN KEY (`serverId`) REFERENCES `items` (`serverId`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
